x-aws-vpc: vpc-0ab94d84a784b412e
x-aws-cluster: arn:aws:ecs:ap-south-1:105178145684:cluster/bayko-test
#x-aws-loadbalancer: ${AWS_ELB}

version: "3.8"
services:
  frontend-react-js:
    image: '105178145684.dkr.ecr.ap-south-1.amazonaws.com/cruddur/frontend-react-js'   
    ports:
      - "80:80"
    environment:
      REACT_APP_BACKEND_URL: "https://aws-b-LoadB-4NFUMCVVHTBO-8909f0ff68812148.elb.ap-south-1.amazonaws.com:4567"
      REACT_APP_AWS_USER_POOLS_ID: "ap-south-1_CQ4wDfnwc"
      REACT_APP_CLIENT_ID: "5b6ro31g97urk767adrbrdj1g5"

  backend-flask:
    image: '105178145684.dkr.ecr.ap-south-1.amazonaws.com/cruddur/backend-flask'
    environment:
      CONNECTION_URL: "${PROD_CONNECTION_URL}" 
      FRONTEND_URL: "https://aws-b-LoadB-4NFUMCVVHTBO-8909f0ff68812148.elb.ap-south-1.amazonaws.com"
      BACKEND_URL: "https://aws-b-LoadB-4NFUMCVVHTBO-8909f0ff68812148.elb.ap-south-1.amazonaws.com:4567"
      AWS_XRAY_URL: "*aws-b-LoadB-4NFUMCVVHTBO-8909f0ff68812148.elb.ap-south-1.amazonaws.com*"
      OTEL_SERVICE_NAME: 'backend-flask'
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      ROLLBAR_ACCESS_TOKEN: "${ROLLBAR_ACCESS_TOKEN}"
      AWS_COGNITO_USER_POOL_ID: "ap-south-1_CQ4wDfnwc"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "5b6ro31g97urk767adrbrdj1g5"

  xray-daemon:
    image: '105178145684.dkr.ecr.ca-central-1.amazonaws.com/cruddur/xray-daemon'